### ISSUE TITLE
Possible compiler bug

### ISSUE THREAD

**Issue by gmlewis** [moonbitlang/moonbit-docs#338] opened 2024-12-03 04:14 UTC
In this repo:
https://github.com/gmlewis/moonbit-ray-tracer/actions/runs/12132793555/job/33827245125

it reports a compiler bug and asks for a bug report.

Here it is:

```
         --  -- 
       /  //  / __--------_
      /  //  /_/            \
   ---      -                \ __
  / X        /        ____   /   )
  *_________/__/_____/______/ `--

Oops, the compiler has encountered an unexpected situation.
This is a bug in the compiler.

A bug report containing the error description and relevant code would be
greatly appreciated. You can submit the bug report here:

failed: moonc check -error-format json /home/runner/work/moonbit-ray-tracer/moonbit-ray-tracer/src/lib/canvas.mbt /home/runner/work/moonbit-ray-tracer/moonbit-ray-tracer/src/lib/color.mbt /home/runner/work/moonbit-ray-tracer/moonbit-ray-tracer/src/lib/tuple.mbt -o /home/runner/work/moonbit-ray-tracer/moonbit-ray-tracer/target/wasm-gc/release/check/lib/lib.mi -pkg gmlewis/ray-tracer/lib -std-path /home/runner/.moon/lib/core/target/wasm-gc/release/bundle -i /home/runner/work/moonbit-ray-tracer/moonbit-ray-tracer/target/wasm-gc/release/check/.mooncakes/gmlewis/image/image.mi:image -pkg-sources gmlewis/ray-tracer/lib:/home/runner/work/moonbit-ray-tracer/moonbit-ray-tracer/src/lib -target wasm-gc
  https://github.com/moonbitlang/moonbit-docs/issues/new?labels=bug,ICE

Error: File "inlined_snapshot/_build/Type_constraint.ml", line 338, characters 16-22: Assertion failed

Compiler args: moonc check -error-format json /home/runner/work/moonbit-ray-tracer/moonbit-ray-tracer/src/lib/canvas.mbt /home/runner/work/moonbit-ray-tracer/moonbit-ray-tracer/src/lib/color.mbt /home/runner/work/moonbit-ray-tracer/moonbit-ray-tracer/src/lib/tuple.mbt -o /home/runner/work/moonbit-ray-tracer/moonbit-ray-tracer/target/wasm-gc/release/check/lib/lib.mi -pkg gmlewis/ray-tracer/lib -std-path /home/runner/.moon/lib/core/target/wasm-gc/release/bundle -i /home/runner/work/moonbit-ray-tracer/moonbit-ray-tracer/target/wasm-gc/release/check/.mooncakes/gmlewis/image/image.mi:image -pkg-sources gmlewis/ray-tracer/lib:/home/runner/work/moonbit-ray-tracer/moonbit-ray-tracer/src/lib -target wasm-gc

moonc version: v0.1.20241202+8[756](https://github.com/gmlewis/moonbit-ray-tracer/actions/runs/12132793555/job/33827245125#step:7:757)d160d
Warning: [1003]
   ╭─[/home/runner/work/moonbit-ray-tracer/moonbit-ray-tracer/.mooncakes/gmlewis/image/image_test.mbt:8:11]
   │
 8 │ typealias Slice[T] = @io.Slice[T]
   │           ──┬──  
   │             ╰──── Warning: Unused type 'Slice'
───╯
error: failed when checking
Error: Process completed with exit code 255.
```

**Comment by peter-jerry-ye** [comment] 2024-12-03 05:37
Minimal example:

```moonbit color/top.mbt
pub(open) trait Color {
  rgba(Self) -> (UInt, UInt, UInt, UInt)
}
```

```moonbit image/top.mbt
pub(open) trait Image {
  at(Self, Int, Int) -> @color.Color
}
```

```moonbit top.mbt
fn f(image : @image.Image) -> Unit {
  let _ = image.at(0, 0).rgba()

}
```

@gmlewis I suspect this is caused by transitive function call. Import `gmlewis/image/color` in the `lib` should solve this problem.

**Comment by gmlewis** [comment] 2024-12-03 16:27
@peter-jerry-ye - that fixed it - thank you!
Do you want to leave this issue open to address the compiler crash?

**Comment by peter-jerry-ye** [comment] 2024-12-04 01:42
No it's fine. We'll have it fixed in the next release.

**Closed by peter-jerry-ye** 2024-12-04 01:42 UTC
